# Generated by Django 4.2.16 on 2024-09-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDXMarketCap',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('idx_total_market_cap', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'idx_market_cap',
            },
        ),
    ]
