# Generated by Django 4.2.16 on 2024-09-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idxmarketcap',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
