# Generated by Django 4.2.16 on 2024-09-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0003_balancesheet_cashflow_incomestatement_indexdaily_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerdaily',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
