# Generated by Django 4.2.16 on 2024-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0004_alter_tickerdaily_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerdaily',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tickerdaily',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
