# Generated by Django 4.2.16 on 2024-09-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0005_alter_tickerdaily_date_alter_tickerdaily_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
