# Generated by Django 4.2.16 on 2024-09-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0007_alter_balancesheet_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='year',
            field=models.CharField(max_length=6),
        ),
    ]
