# Generated by Django 4.2.16 on 2024-09-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0008_alter_balancesheet_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerOverview',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('sub_sector', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('sub_industry', models.CharField(max_length=255)),
                ('listing_date', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ticker_overview',
            },
        ),
    ]
