# Generated by Django 4.2.16 on 2024-09-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0009_tickeroverview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickeroverview',
            name='listing_date',
            field=models.CharField(max_length=20),
        ),
    ]
