# Generated by Django 4.2.16 on 2024-09-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0010_alter_tickeroverview_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idxmarketcap',
            name='idx_total_market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
