# Generated by Django 4.2.16 on 2024-09-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0011_alter_idxmarketcap_idx_total_market_cap'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='idxmarketcap',
            table='idx_total_market_cap',
        ),
    ]
