# Generated by Django 4.2.16 on 2024-09-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0012_alter_idxmarketcap_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDXMarketCap',
        ),
    ]
