# Generated by Django 4.2.16 on 2024-09-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0013_delete_idxmarketcap'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDXTotalMarketCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('idx_total_market_cap', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'idx_total_market_cap',
            },
        ),
    ]
