# Generated by Django 4.2.16 on 2024-09-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0015_tickerlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TickerList',
        ),
    ]
