# Generated by Django 4.2.16 on 2024-09-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0016_delete_tickerlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'idx_tickers',
            },
        ),
    ]
