# Generated by Django 4.2.16 on 2024-09-12 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0017_tickerlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceSheet',
        ),
    ]
