# Generated by Django 4.2.16 on 2024-09-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfin_app', '0018_delete_balancesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=6)),
                ('symbol', models.CharField(max_length=10)),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('total_debt', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'balance_sh',
            },
        ),
    ]
